---
title: "DM001-7"
author: "Becky Mak"
date: "Monday, February 23, 2015"
output: html_document
---
Copied from library(arulesSequences) example to convert data into sequence
```{r echo=FALSE}
library(arules)
library(arulesSequences)

## 3 example sequences
x <- list("01" = list(c("A","B"), "C"),
"02" = list("C"),
"03" = list("B", "B"))
## coerce
s <- as(x, "sequences")
as(s, "data.frame")
## get reference set
as(itemsets(s), "data.frame")

```

```{r echo=FALSE}
list1 = c("bd.c.b.ac","bf.ce.b.fg",
          "ah.bf.a.b.f","be.ce.d",
          "a.bd.b.c.b.ade")
list2 = unlist(lapply(list1, strsplit, split="[.]"),recursive=FALSE)
list3 = lapply(list2, as.list)
library(reshape2)
data = dcast(cbind(
  coln = sequence(rapply(list3, length)), 
  melt(list3)), L1 + L2 ~ coln, 
  value.var = "value")
names(data) = c("sequenceID", "eventID", "items")

data$SIZE = as.integer(lapply(data$items, nchar))
data = data[,c("items", "sequenceID","eventID","SIZE")]

items = strsplit(data$items, split="")
ncol = max(sapply(items,length))
items_list = lapply(items, function(x) paste(x , collapse=" "))
items_col = data.frame(t(do.call(cbind, items_list)))

data = cbind(data[,c(2:4)], items_col)

#write.table(data, file="dm_001_7_2.txt", sep="\t", row.names=FALSE, col.names=FALSE, na="")
```
```{r}
library(RCurl)
path = getURL("https://raw.githubusercontent.com/beckymak/DataMining/master/Pattern%20Discovery%20in%20Data%20Mining/dm_001_7_2.txt")

zz <- file("test")  
cat(path, file = zz, sep = "")

library(arules)
library(arulesSequences)

trans = read_baskets(zz, sep = "\t",info =  c("sequenceID","eventID","size"))
inspect(trans)
as(trans, "transactions")
#closed = cspade(trans)  ## not ok yet
#inspect(closed)

s1 = apriori(trans, parameter = list(confidence=0.2))
#s1 = cspade(trans, parameter = list(support = 0.4),control = list(verbose = TRUE))
#summary(s1)
itemFrequency(trans,itemsets=TRUE)


```

